use std::env;
use std::path::PathBuf;

use crate::indices::Indices;

/// Site-specific Rust-source templating for one resource. Each consumer
/// implements this with its own shape (`dataspace/site`'s `ClassInfo`,
/// `www`'s bilingual `PageContent`) rather than this crate imposing one
/// generic emitted shape on every consumer.
pub trait CodegenEmitter {
  /// Rust source fragment for `resource_iri` (typically one or more `pub
  /// const` items).
  fn emit(&self, indices: &Indices, resource_iri: &str) -> String;
}

/// Concatenates `emitter.emit(..)` over `resources`, in the order given,
/// prefixed with a "generated, do not edit by hand" header comment.
pub fn generate_rust_module(emitter: &dyn CodegenEmitter, indices: &Indices, resources: &[&str]) -> String {
  let mut out = String::from("// Generated by build.rs via rdf-sitegen -- do not edit by hand, edit the ontology source instead.\n\n");
  for resource_iri in resources {
    out.push_str(&emitter.emit(indices, resource_iri));
  }
  out
}

/// Writes `content` to `OUT_DIR/filename` (unconditionally — `OUT_DIR` is
/// already cargo-managed and isn't `cargo:rerun-if-changed`-watched by the
/// caller, so it doesn't need [`crate::write_if_changed`]'s rerun-loop
/// guard). Returns the path written.
pub fn write_out_dir_file(filename: &str, content: &str) -> PathBuf {
  let out_dir = env::var("OUT_DIR").expect("OUT_DIR not set by cargo -- write_out_dir_file must be called from a build.rs");
  let path = PathBuf::from(out_dir).join(filename);
  std::fs::write(&path, content).unwrap_or_else(|e| panic!("failed to write {}: {e}", path.display()));
  path
}
